/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.arenda;

public final class R {
    public static final class attr {
    }
    public static final class string {
        public static final int url_p=0x7f020001;
        public static final int url_p_old=0x7f020000;
    }
}
