/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.testapk138;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int btnLocationSettings=0x7f040000;
        public static final int btnSMS=0x7f040001;
        public static final int tvEnabledGPS=0x7f040003;
        public static final int tvEnabledNet=0x7f040007;
        public static final int tvLocationGPS=0x7f040005;
        public static final int tvLocationNet=0x7f040009;
        public static final int tvSmsSoob=0x7f04000a;
        public static final int tvStatusGPS=0x7f040004;
        public static final int tvStatusNet=0x7f040008;
        public static final int tvTitleGPS=0x7f040002;
        public static final int tvTitleNet=0x7f040006;
    }
    public static final class layout {
        public static final int main=0x7f020000;
    }
    public static final class string {
        public static final int location_settings=0x7f030002;
        public static final int provider_gps=0x7f030000;
        public static final int provider_network=0x7f030001;
        public static final int send_sms=0x7f030003;
    }
}
